# Site settings
title: BornToBeRoot
description: 'Add description here...'
url: 'https://borntoberoot.net'
baseurl: ''
profilepic: '/images/borntoberoot.png'
bkimage: '/images/bk1.jpg'
#google_analytics: UA-XXXXXX-X
font_awesome: 'd7ef2b00f2.js'

author:
  name: 'BornToBeRoot'
# email: xxx@xxx.xx
  twitter_username: BornToBeRoot_DE
#  facebook_username: xxx
  github_username:  BornToBeRoot
#  linkedin_username:  xxx
#  meetup_name: xxx

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false